import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

// Turns the drizzle-kit-generated .sql files in migrations/ into a plain TS module. Neither
// backend (node:sqlite in tests, sqlocal/OPFS in the browser) can read files off disk at runtime,
// so this is the bridge: drizzle-kit generate produces the .sql (source of truth for schema
// diffing), this script bundles it into src/migrations-data.ts (source of truth at runtime). Run
// after every `db:generate`.
const migrationsDir = new URL("../migrations", import.meta.url).pathname;
const outFile = new URL("../src/migrations-data.ts", import.meta.url).pathname;

const files = readdirSync(migrationsDir)
  .filter((name) => name.endsWith(".sql"))
  .sort();

const migrations = files.map((file) => {
  const content = readFileSync(path.join(migrationsDir, file), "utf8");
  const statements = content
    .split("--> statement-breakpoint")
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0);
  return { name: file.replace(/\.sql$/, ""), statements };
});

const body = `// GENERATED by scripts/build-migrations.ts — do not edit by hand. Re-run after db:generate.
export interface LocalStoreMigration {
  name: string;
  statements: string[];
}

export const MIGRATIONS: LocalStoreMigration[] = ${JSON.stringify(migrations, null, 2)};
`;

writeFileSync(outFile, body);
console.log(`Wrote ${migrations.length} migration(s) to src/migrations-data.ts`);
