// GENERATED by scripts/build-migrations.ts — do not edit by hand. Re-run after db:generate.
export interface LocalStoreMigration {
  name: string;
  statements: string[];
}

export const MIGRATIONS: LocalStoreMigration[] = [
  {
    "name": "0000_fine_orphan",
    "statements": [
      "CREATE TABLE `conversation_cursors` (\n\t`conversation_id` text PRIMARY KEY NOT NULL,\n\t`last_seen_seq` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);",
      "CREATE TABLE `outbox` (\n\t`client_id` text PRIMARY KEY NOT NULL,\n\t`conversation_id` text NOT NULL,\n\t`content_type` text NOT NULL,\n\t`payload` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`status` text DEFAULT 'pending' NOT NULL\n);",
      "CREATE TABLE `timeline_entries` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`conversation_id` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`envelope_id` text,\n\t`sender_id` text,\n\t`sender_device_id` text,\n\t`seq` integer,\n\t`content_type` text,\n\t`payload` text,\n\t`created_at` integer NOT NULL,\n\t`gap_from_seq` integer,\n\t`gap_to_seq` integer\n);",
      "CREATE UNIQUE INDEX `timeline_entries_envelope_id_unique` ON `timeline_entries` (`envelope_id`);",
      "CREATE INDEX `timeline_entries_conversation_id_idx` ON `timeline_entries` (`conversation_id`,`id`);"
    ]
  }
];
